sources:
  - table: orders
    type: csv
    path: ./sources/orders.csv

  - table: products
    type: csv
    path: ./sources/products.csv

  - table: customers
    type: csv
    path: ./sources/customers.csv

  - table: departments
    type: csv
    path: ./sources/departments.csv

  - table: regions
    type: csv
    path: ./sources/regions.csv

  # Example HTTP source with auth (uncomment to use):
  # - table: api_data
  #   type: json
  #   path: https://api.example.com/data.json
  #   headers:
  #     Authorization: "Bearer ${API_TOKEN}"

  # duckdb -c "COPY (SELECT * FROM 'example/sources/milestones.csv') TO 'example/sources/milestones.parquet'"
  - table: gitlab_milestones
    type: parquet
    path: ./sources/milestones.parquet
