sources:
  orders:
    type: csv
    path: ./sources/orders.csv
    description: Order transactions

  products:
    type: csv
    path: ./sources/products.csv
    description: Product catalog

  customers:
    type: csv
    path: ./sources/customers.csv
    description: Customer information
