sources:
  orders:
    type: csv
    path: ./sources/orders.csv
    description: Order transactions

  products:
    type: csv
    path: ./sources/products.csv
    description: Product catalog

  customers:
    type: csv
    path: ./sources/customers.csv
    description: Customer information

  departments:
    type: csv
    path: ./sources/departments.csv
    description: Department metrics

  regions:
    type: csv
    path: ./sources/regions.csv
    description: Regional sales data
